### ISSUE TITLE
Precise the chipset in CONSOLE_MIRRORING.md

### ISSUE THREAD

**Issue by St0wy** [project-slippi/slippi-wiki#25]
In CONSOLE_MIRRORING.md, the required chipset is `ASIX AX88772` an not `ASIX AX88772A`. I have tried with a `ASIX AX88772B` and it doesn't work. The google doc version has this precision by the way.

**Comment by NikhilNarayana** [comment]
Honestly I just don't want to put in the effort to maintain those so I'm just going to make all those link to the google docs instead.
