### ISSUE TITLE
Item update payload won't account for valid game states even without items

### ISSUE THREAD

**Issue by Summate** [project-slippi/slippi-wiki#3]
For example, there can be 4 G&W players all using bacon. There can be 5 bacons on screen at a time. This is 20 bacons and the constant of 15 doesn't allow for this. Sheik can spit out 6 needles in a full batch, 4 * 6 is 24.

In general there are things like character-specific state data and projectile data that may be useful to be variable-sized and there's no mechanism in the spec to allow this. However adding variable-sized payloads doesn't work well as the spec is currently designed.

**Comment by JLaferri** [comment]
Variable size payloads are not allowed but variable number of events is allowed. The way items are currently defined, that's how the work. If they exist, they get one event payload on that frame. This is nearly equivalent to if there was one "item update" per frame that included all items of variable size.

While the limit could be increased, I think 15 is a good enough number for now that should account for most "normal" games. Currently nobody is using the item payload anyway, we can consider increasing the amount in the future.

**Comment by JLaferri** [comment]
Closing this for now. More discussion about this can be found here: https://discordapp.com/channels/328261477372919811/417153381249974272/646134649692749844
